config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :comments

  resources :questions do
    resources :answers, except: [:show] do
      resources :comments, except: [:show], module: :answers
      resources :votes, only:[:create,:update, :destroy], module: :answers
    end
    resources :votes, only:[:create,:update, :destroy], module: :questions
    resources :comments, except: [:show], module: :questions
  end

  root 'questions#index'
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id         :integer          not null, primary key
#  title      :string
#  body       :text
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Question < ApplicationRecord
  has_many :comments, as: :commentable
  has_many :votes, as: :voteable
  has_many :answers
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true

end

app/controllers/questions/comments_controller.rb
class Questions::CommentsController < CommentsController
  before_action :set_commentable

  def create
   super
  end

  private

    def set_commentable
      @commentable = Question.find(params[:question_id])
    end
end

app/controllers/questions/votes_controller.rb
class Questions::VotesController < VotesController
  before_action :set_voteable

  private

    def set_voteable
      @voteable = Question.find(params[:question_id])
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_question, only: [:show, :edit, :update, :destroy]

  def index
    @questions = Question.all
    if params[:title].present?
      @questions = @questions.where("title LIKE ?", "%#{params[:title].capitalize}%").page(params[:page]).per(4)
    else
      @questions = Question.all.order("created_at DESC").page(params[:page]).per(4)
    end
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_user
    if @question.save
      redirect_to root_path, notice: 'Question saved...'
    else
      redirect_to new_question_path, flash: { alert: 'question could not be announced...' } 
    end
  end

  def show
  end

  private

		def question_params
			params.require(:question).permit(:title, :body, :user_id)
		end

		def find_question
			@question = Question.find(params[:id])
		end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def form_title
    @question.new_record? ? "New Question" : "Edit Question"
  end

  def answers_by_questions
       question.answers.count
  end
end

app/views/questions/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-5 col-md-offset-3">

      <h2 class="text-center">Post a question</h2>
      <br/>

      <%= form_for @question do |f| %>
           <%= render "shared/message" %>

        <div class="form-group">
          <%= f.text_field :title, autofocus: true, placeholder: "Title", class: "form-control" %>
        </div>

        <div class="form-group">
           <%= md_simple_editor  do %>
              <%= f.text_area :body, autofocus: true, :rows => 6, style: 'width:100%;', placeholder: "Description", class: "form-control" %>
           <% end %>
        </div>

        <div class="actions">
          <%= f.submit "¡Ask!", class: "btn btn-primary btn-lg btn-block" %>
        </div>
      <% end %>

    <div/>
  </div>
</div>

app/views/questions/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-10 col-sm-offset-1">
      <h1>Questions</h1>
    </div>
  </div>
  <div class= "questions"> <!-- begin questions-->
     <div class="row">
          <div class="question clearfix">
              <div class="col-sm-10 col-sm-offset-1 button-ask-question">
                <div class="button-ask-question">
                  <%=  link_to "Ask a question", new_question_path, :method => :get, class: "btn btn-primary" %>
                </div>
              </div>
          </div>
     </div>
    <div class="row">
      <div class="col-sm-10 col-sm-offset-1"> <!-- begin col-sm-10-->
      <hr>
        <% unless @questions.nil? %>
            <% @questions.each do |question| %>
               <div class="question-details">
                <div class="row"> <!-- begin row -->
                  <div class="col-sm-1 data"><!-- begin col-1-->
                    <span><%= question.votes.count  %></span>
                    <span><h5 class="data-label">Votes</h5></span>
                  </div> <!-- end col-1-->
                  <div class="col-sm-1 data"><!-- begin col-2-->
                    <span><span><%= question.answers.count  %></span></span>
                    <span><h5 class="data-label">Answers</h5></span>
                  </div> <!-- end col.2-->
                  <div class="col-sm-10"> <!-- begin cols-2-->
                    <h2 class="question-title"><%= link_to question.title, question %></h2>
                      <div class="asked">    Asked: <%= question.user.fullname %> <%= time_ago_in_words(question.created_at) %> </div>
                  </div><!-- end cols-3-->
                </div>  <!-- end row -->
               </div>
               <hr>
            <% end %>
            <%= paginate(@questions) %>
        <% end %>
        <br>
      </div> <!-- end col-sm-10-->
    </div>
  </div> <!-- end questions-->
  <br>
</div>

app/views/questions/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-sm-8 col-sm-offset-1">
            <h2 class="title-question"><%= @question.title %></h2>
        </div>
    </div>
    <div class="questions">
        <% if user_signed_in? %>
            <div class="row">
              <div class="col-sm-1 col-sm-offset-1">
                <% vote = Vote.voted_by?(current_user,  @question) %>
                <% if vote %>
                      <%= link_to question_vote_path(@question, vote), remote: true, method: :delete, class: "question-upvote upvote-active" do %>
                          <span class="upvote-arrow"></span>
                          <span class="upvote-count"><%= @question.votes.count %></span>
                      <% end %>
                <% else %>
                      <%= link_to question_votes_path(@question), remote: true, method: :post, class: "question-upvote" do %>
                          <span class="upvote-arrow"></span>
                          <span class="upvote-count"><%= @question.votes.count %></span>
                      <% end %>
                <% end %>
                </div>
                <div class="col-sm-8 body-show-question">
                    <span> <%= markdown(@question.body) %> </span>
                    <span class="comments">
                      <%= render partial: "comments/comments", locals: {commentable: @question} %>
                    </span>
                      <%= render partial: "comments/form", locals: {commentable: [@question]} %>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-8 col-sm-offset-1">
                    <h2>(<%= @question.answers.count %>) Answer(s)</h2>
                </div>
            </div>
            <% @question.answers.each do |answer|  %>
                <div class="row">
                  <div class="col-sm-1 col-sm-offset-1">
                    <% vote = Vote.voted_by?(current_user, answer) %>
                    <% if vote %>
                          <%= link_to question_answer_vote_path(@question, answer), remote: true, method: :delete, class: "question-upvote upvote-active" do %>
                              <span class="upvote-arrow"></span>
                              <span class="upvote-count"><%= answer.votes.count %></span>
                          <% end %>
                    <% else %>
                        <%= link_to question_answer_votes_path(@question, answer, vote), remote: true, method: :post, class: "question-upvote" do %>
                                <span class="upvote-arrow"></span>
                                <span class="upvote-count"><%= answer.votes.count %></span>
                        <% end %>
                    <% end %>
                  </div>
                  <div class="col-sm-8 body-show-question">
                        <span> <%= markdown(answer.body) %> </span>
                        <span class="comments">
                          <%= render partial: "comments/comments", locals: {commentable: answer} %>
                        </span>
                          <%= render partial: "comments/form", locals: {commentable: [answer.question, answer]} %>
                  </div>
                </div>
            <% end %> <!-- end do |answer|-->
            <div class="row">
                <div class="col-sm-8 col-sm-offset-1">
                    <h3 class="head-answer">Your answer</h3>
                    <%= render partial: "answers/form", locals: {question: @question} %>
                </div>
            </div>
        <% else %>
            <div class="row">
                <div class="col-sm-1 col-sm-offset-1">
                    <div class="question-upvote">
                        <span class="upvote-arrow"></span>
                        <span class="upvote-count"><%= @question.votes.count %></span>
                    </div>
               </div>
               <div class="col-sm-8 body-show-question">
                    <span> <%= markdown(@question.body) %> </span>
                    <span class="comments">
                        <%= render partial: "comments/comments", locals: {commentable: @question} %>
                    </span>
               </div>
            </div>
            <div class="row">
                <div class="col-sm-8 col-sm-offset-1 ">
                    <div>
                        <h2>(<%= @question.answers.count %>) Answer(s)</h2>
                    </div>
                </div>
           </div>
          <% @question.answers.each do |answer|  %>
            <div class="row">
                <div class="col-sm-1 col-sm-offset-1">
                  <div class="question-upvote">
                     <span class="upvote-arrow"></span>
                     <span class="upvote-count"><%= answer.votes.count %></span>
                  </div>
                </div>
                <div class="col-sm-8 body-show-question">
                      <span> <%= markdown(answer.body) %> </span>
                      <span class="comments">
                        <%= render partial: "comments/comments", locals: {commentable: answer} %>
                      </span>
                </div>
            </div>
          <% end %> <!-- end do |answer|-->
    </div><!-- end  class questions-->
  <% end %>
</div>