config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :comments

  resources :questions do
    resources :answers, except: [:show] do
      resources :comments, except: [:show], module: :answers
      resources :votes, only:[:create,:update, :destroy], module: :answers
    end
    resources :votes, only:[:create,:update, :destroy], module: :questions
    resources :comments, except: [:show], module: :questions
  end

  root 'questions#index'
end

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
  <script type="text/javascript">
    <% resource.errors.full_messages.each do |value| %>
      toastr.error('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
    <script type="text/javascript">
      <% flash.each do |key, value| %>
        <% type = key.to_s.gsub('alert','error').gsub('notice','success') %>
        toastr['<%= type %>']('<%= value %>')
      <% end %>
    </script>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top navbar-inverse" >
    <div class="container">
      <div class="row">
        <div class="col-sm-10 col-sm-offset-1">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to "StackOverFlow", root_path, class: "navbar-brand" %>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <% if signed_in? %>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle avatar" data-toggle="dropdown">
                      <img src="<%= Gravatar.new("#{current_user.email}").image_url %>" class="img-circle" />
                      &nbsp <div class="fullname"><%= current_user.fullname %></div> <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu" role="menu">
                        <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
                    </ul>
                  </li>
                <% else %>
                  <li><%= link_to "Sign up", new_user_registration_path %></li>
                  <li><%= link_to "Sign in", new_user_session_path %></li>
                <% end %>
            </ul>
            <form class="navbar-form navbar-right" role="search">
              <%= form_tag questions_path, method: :get do %>
                <div class="form-group">
                  <%= text_field_tag :title, params[:title], class: "form-control", placeholder: "Search" %>
                </div>
              <% end %>
            </form>
          </div><!-- /.navbar-collapse -->
        </div>
      </div>
    </div><!-- /.container -->
  </nav>