config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :comments

  resources :questions do
    resources :answers, except: [:show] do
      resources :comments, except: [:show], module: :answers
      resources :votes, only:[:create,:update, :destroy], module: :answers
    end
    resources :votes, only:[:create,:update, :destroy], module: :questions
    resources :comments, except: [:show], module: :questions
  end

  root 'questions#index'
end

app/models/answer.rb
# == Schema Information
#
# Table name: answers
#
#  id          :integer          not null, primary key
#  body        :text
#  user_id     :integer
#  question_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Answer < ApplicationRecord
  has_many :comments, as: :commentable
  has_many :votes, as: :voteable
  belongs_to :user
  belongs_to :question

  validates :body, presence: true
end

app/controllers/answers/comments_controller.rb
class Answers::CommentsController < CommentsController
  before_action :set_commentable

  def create
    super
  end

  private

    def set_commentable
      @commentable = Answer.find(params[:answer_id])
    end
end

app/controllers/answers/votes_controller.rb
class Answers::VotesController < VotesController
  before_action :set_voteable

  private

    def set_voteable
      @voteable = Answer.find(params[:answer_id])
    end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_answer, only: [:show, :edit, :update, :destroy]
  before_action :current_question, only: [:show, :create]

  def new
    @answer = question.answers.build
    render :layout => false
  end

  def create
    @answer = @question.answers.build(answer_params)
    @answer.user = current_user
    if @answer.save
      redirect_to question_path(@question), notice: 'Answer saved...'
    else
      redirect_to question_path(@question), flash: { alert: "Your answer wasn't posted..." }
    end
  end

  private

		def answer_params
			params.require(:answer).permit(:body)
		end

		def find_answer
			@answer = Answer.find(params[:id])
		end


		def current_question
			  @question = Question.find(params[:question_id])
		end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-7 col-sm-offset-1">
     <%= form_for :answer, url: question_answers_path(question.id) do |f| %>
      <div class="form-group mkdown_answer">
         <%= md_simple_editor  do %>
            <%= f.text_area :body, autofocus: true, :rows => 6, style: 'width:100%;', placeholder: "Answer", class: "form-control" %>
         <% end %>
      </div>
      <div class="actions mkdown_button">
        <%= f.submit "Send answer", class: "btn btn-primary btn-lg btn-block" %>
      </div>
    <% end %>
    <div/>
  </div>
 </div>
</div>

app/views/answers/new.html.erb
<%=  render 'form' %>